### PR TITLE
Add new strings file for es-ES.

### PR DESCRIPTION
**Pull request by timbergus**
I have added translations for the Spanish language from Spain.

### CODE REVIEW

**Comment by SachaG** [comment]
Thanks a ton!

By the way we also have a Spanish (Latam) version: https://github.com/StateOfJS/StateOfJS-Vulcan/pull/40 by @ezakto 

As I'm not really qualified to figure it out, I'll let you two decide if we need two different Spanish versions or not. I'm not against it fundamentally but it does mean more work going forward every time we add new surveys or new text strings.

How do other projects handle this issue? Is having both options common? For example I noticed Wikipedia only has https://es.wikipedia.org/ (as far as I can tell), did they manage to use neutral language or does this mean they're actually using `es_ES` and latin american Spanish speakers are left out?

**Comment by ezakto** [comment]
Having both options is nice and common, but having es-ES only is pretty common too and I don't think it'd be a problem.
Wikipedia doesn't have clear guidelines about it, except for a few conventions (like for movie titles or animal names), so you can find articles using one or another locale, or even mixed.

**Comment by SachaG** [comment]
How about this: if there are specific places where the two versions differ (beyond just stylistic choices) we'll keep both, if not we can merge them or keep only one?

**Comment by timbergus** [comment]
You're welcome @SachaG 👍

I don't think that talking about technical language, we are going to have so many differences between both files. Both options sound good to me. I don't know the differences between Argentina and Spain, colloquial expressions, so if @ezakto wants, he can, for example, check my translations, and add comments, or add the common parts to his. I think the idea is to remove the expressions that can create confusion in one place or the other.

**Comment by SachaG** [comment]
@ezakto what do you think? how do you want to proceed?

**Comment by timbergus** [comment]
OK, @ezakto and @SachaG. What do you think about this? We can go on with the `es_ES` files, as the Spanish base translation (kind of international Spanish), and then we can modify all the parts that can create confusion. As I mentioned before, these are mostly technical contents, so there shouldn't be a lot of complex expressions. And instead of having different versions, we just can add corrections from different people in the future. We could create a multicultural Spanish translation that suits everyone.

**Comment by ezakto** [comment]
Oh, sorry. I think I wasn't clear enough. I think for the sake of maintainability having just es_ES is the best option, and the latam community would be just fine with it.

**Comment by SachaG** [comment]
Ok great, thanks for being flexible! I'll merge this one in that case.

**Pull request merged**
