### PR TITLE
Italian Translation

### PR DESCRIPTION
**Pull request by polettoweb**
#### COMMON

- [x] General
- [x] Nav
- [x] Accounts
- [x] Sections
- [x] Options
- [x] Tools
- [x] Demographics
- [x] Other Tools
- [x] Resources

#### RESULTS

- [x] General
- [x] Tools & Methodologies

#### STATE-OF-CSS

- [x] General
- [x] Sections
- [x] Options
- [x] Features
- [x] Units & Selectors
- [x] Tools
- [x] Environments
- [x] Opinions

#### STATE-OF-JS
- [x] General
- [x] Sections
- [x] Options
- [x] Features
- [x] Opinions

### CODE REVIEW

**Comment by SachaG** [comment]
Great work, that was fast! I'll test it out tomorrow :)

**Comment by polettoweb** [comment]
Done. Everything should be ready to be PRed ;-)

**Comment by polettoweb** [comment]
I've added the new requested translations and noticed a typo in the new US version lines 268-269 are repetitions https://github.com/StateOfJS/StateOfJS-Vulcan/blob/ad78403a2391bee80b039a971ff75d6d2cabc146/packages/stateofjs/lib/i18n/state-of-css/yml/en-US.yml#L268

**Comment by SachaG** [comment]
Great, awesome work!

**Comment by SachaG** [comment]
I deployed the translation, having the questions translated is so cool! You can check it out here:

https://survey.stateofjs.com/survey/state-of-css/2020

Btw I noticed you didn't translate the string for "Account"? (`nav.account` in `common.yml`), was that on purpose?

And I also added a few more strings (sorry!): 

- https://github.com/StateOfJS/StateOfJS-Vulcan/commit/7038b411058bf8e00c1c48b3f7ab26052a80eae6#diff-c97a3dab92e66d7d2b4f45531b0e6d2a
- https://github.com/StateOfJS/StateOfJS-Vulcan/commit/46ccf38e5a4083284b486138e3b1785450e4b3b9#diff-7e677223cfa190e142a85c749b9b3420

**Comment by SachaG** [comment]
Oh also I didn't catch it before but I think for some CSS properties like `perspective`, `direction`, we should leave the actual english name of the property rather than translate it. Or maybe we need to add some `<code></code>` styling to make it clear that it's a property name?

**Comment by polettoweb** [comment]
I did left a lot of them as original. I changed only the one that will be
understandable anyway.

**Pull request merged**
