### PR TITLE
Spanish translation (Argentina)

### PR DESCRIPTION
**Pull request by ezakto**

### CODE REVIEW

**Comment by SachaG** [comment]
Great! Btw I'm not familiar with the differences between Spanish as spoken in Spain and Spanish as spoken in Argentina but if they're similar then I would probably prefer having a single "neutral" version that works for as many people as possible, assuming such a thing is possible.

**Comment by ezakto** [comment]
Yeah, I think it's possible. Spanish from Spain usually uses little to no anglicisms, while Spanish from Argentina (and from Latin America overall) is more flexible in that aspect. I can give it a shot, though. Would you like a separate PR, to keep things a bit more organized?

**Comment by SachaG** [comment]
As you prefer, I would just like to avoid the situation where we have another PR for `es_ES` and we then have to decide what to do (because having "Español" twice in the menu would be very confusing…). But I can also see that it would be frustrating for Latin Americans to never have their way of using the language represented in translations.

**Comment by ezakto** [comment]
Okay, I see your point. I made an es-AR version only because it was faster for me to translate plus I thought the more locales would be the better. I can see how that'd be harder to maintain though.
Spaniards are more protective of their use of the language, while Latin Americans are usually fine with anything (we all share the same "neutral" Latam Spanish for entertainment, papers, etc), so that's why most of the time you'll see two versions of Spanish (`Spanish EU` or `Spanish (Spain)` and `Spanish LA` or `Spanish (Latam)`).
The best I can do is going for Spanish Latam (aka [es-419](https://www.localeplanet.com/icu/es-419/index.html)) as I don't think I can do a well written es-ES translation. I hope it'll be helpful enough!

**Comment by ezakto** [comment]
Closed in favor of #40

**Pull request closed without merging**
